// Generated by GravityQA - Automated Test
// Date: 2025-12-20 18:52

const { remote } = require('webdriverio');

async function runTest() {
    // Connect to Appium server
    const driver = await remote({
        hostname: 'localhost',
        port: 4723,
        capabilities: {
            platformName: 'Android',
            'appium:automationName': 'UiAutomator2',
            'appium:deviceName': 'Android Device',
            // Add your app package/activity here
        }
    });

    try {
        // Step 1: Tap at (567, 1347)
        await driver.touchAction({ action: 'tap', x: 567, y: 1347 });

        // Step 2: Tap at (529, 1546)
        await driver.touchAction({ action: 'tap', x: 529, y: 1546 });

        // Step 3: Tap at (96, 222)
        await driver.touchAction({ action: 'tap', x: 96, y: 222 });

        console.log('✅ Test completed successfully!');

    } catch (error) {
        console.error('❌ Test failed:', error);
        throw error;
    } finally {
        await driver.deleteSession();
    }
}

// Run the test
runTest().catch(console.error);