// Generated by GravityQA - Automated Test
// Date: 2025-12-21 03:19

// INSTALLATION REQUIRED:
// Before running, install dependencies: npm install webdriverio

const { remote } = require('webdriverio');

async function runTest() {
    // Connect to Appium server
    const driver = await remote({
        hostname: 'localhost',
        port: 4723,
        capabilities: {
            platformName: 'Android',
            'appium:automationName': 'UiAutomator2',
            'appium:deviceName': 'Android Device',
            // Add your app package/activity here
        }
    });

    try {
        // Step 1: Tap at (576, 1324)
        await driver.touchAction({ action: 'tap', x: 576, y: 1324 });

        // Step 2: Tap at (636, 1561)
        await driver.touchAction({ action: 'tap', x: 636, y: 1561 });

        // Step 3: Tap at (102, 222)
        await driver.touchAction({ action: 'tap', x: 102, y: 222 });

        console.log('✅ Test completed successfully!');

    } catch (error) {
        console.error('❌ Test failed:', error);
        throw error;
    } finally {
        await driver.deleteSession();
    }
}

// Run the test
runTest().catch(console.error);