// Generated by GravityQA - Automated Test
// Date: 2025-12-21 04:03

// ═══════════════════════════════════════════════════════════
// 🎯 APP CONFIGURATION
// ═══════════════════════════════════════════════════════════

const APP_CONFIG = {
    package: 'com.example.app',
    activity: 'com.example.app.MainActivity',
    clearAppDataBeforeLaunch: true,  // Clear app cache/data before test
};

const { remote } = require('webdriverio');

async function runTest() {
    console.log('🚀 Starting test...');
    console.log(`📱 App: ${{APP_CONFIG.package}}`);
    console.log(`🎯 Activity: ${{APP_CONFIG.activity}}`);
    
    // Connect to Appium server
    const driver = await remote({
        hostname: 'localhost',
        port: 4723,
        capabilities: {
            platformName: 'Android',
            'appium:automationName': 'UiAutomator2',
            'appium:deviceName': 'Android Device',
            
            // ═══════════════════════════════════════════
            // 📦 APP SETTINGS
            // ═══════════════════════════════════════════
            'appium:appPackage': APP_CONFIG.package,
            'appium:appActivity': APP_CONFIG.activity,
            
            // ═══════════════════════════════════════════
            // 🧹 CLEAR APP DATA (Fresh Start)
            // ═══════════════════════════════════════════
            'appium:noReset': !APP_CONFIG.clearAppDataBeforeLaunch,
            'appium:fullReset': APP_CONFIG.clearAppDataBeforeLaunch,
        }
    });

    try {
        console.log('✅ Connected to device');
        
        if (APP_CONFIG.clearAppDataBeforeLaunch) {
            console.log('🧹 App data cleared - Fresh start!');
        }
        
        console.log('🎬 Starting test steps...');

        // Step 1: Tap at (533, 1295)
        await driver.performActions([{
            type: 'pointer',
            id: 'finger1',
            parameters: { pointerType: 'touch' },
            actions: [
                { type: 'pointerMove', duration: 0, x: 533, y: 1295 },
                { type: 'pointerDown', button: 0 },
                { type: 'pause', duration: 100 },
                { type: 'pointerUp', button: 0 }
            ]
        }]);

        // Step 2: Tap at (727, 1553)
        await driver.performActions([{
            type: 'pointer',
            id: 'finger1',
            parameters: { pointerType: 'touch' },
            actions: [
                { type: 'pointerMove', duration: 0, x: 727, y: 1553 },
                { type: 'pointerDown', button: 0 },
                { type: 'pause', duration: 100 },
                { type: 'pointerUp', button: 0 }
            ]
        }]);

        // Step 3: Tap at (127, 222)
        await driver.performActions([{
            type: 'pointer',
            id: 'finger1',
            parameters: { pointerType: 'touch' },
            actions: [
                { type: 'pointerMove', duration: 0, x: 127, y: 222 },
                { type: 'pointerDown', button: 0 },
                { type: 'pause', duration: 100 },
                { type: 'pointerUp', button: 0 }
            ]
        }]);

        console.log('✅ Test completed successfully!');

    } catch (error) {
        console.error('❌ Test failed:', error);
        throw error;
    } finally {
        await driver.deleteSession();
        console.log('👋 Session closed');
    }
}

// Run the test
runTest().catch(console.error);