"""Code Generator - Convert recorded actions to executable code"""

def generate_javascript_code(actions: list) -> str:
    """Generate WebdriverIO/JavaScript code from actions"""
    
    code_lines = [
        "// Generated by GravityQA - Automated Test",
        "// Date: " + str(__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')),
        "",
        "const { remote } = require('webdriverio');",
        "",
        "async function runTest() {",
        "    // Connect to Appium server",
        "    const driver = await remote({",
        "        hostname: 'localhost',",
        "        port: 4723,",
        "        capabilities: {",
        "            platformName: 'Android',",
        "            'appium:automationName': 'UiAutomator2',",
        "            'appium:deviceName': 'Android Device',",
        "            // Add your app package/activity here",
        "        }",
        "    });",
        "",
        "    try {",
    ]
    
    for i, action in enumerate(actions, 1):
        action_type = action.get('action', 'tap')
        x = action.get('x', 0)
        y = action.get('y', 0)
        
        code_lines.append(f"        // Step {i}: {action.get('description', action_type)}")
        
        if action_type == 'tap':
            # Check if element has selector
            element = action.get('element', {})
            selector = element.get('selector', {})
            
            if selector and selector.get('value'):
                strategy = selector.get('strategy', 'xpath')
                value = selector.get('value', '')
                
                if strategy == 'id':
                    code_lines.append(f"        await driver.$('id={value}').click();")
                else:
                    code_lines.append(f"        await driver.$('{value}').click();")
            else:
                # Modern W3C actions for tap
                code_lines.append(f"        await driver.performActions([{{")
                code_lines.append(f"            type: 'pointer',")
                code_lines.append(f"            id: 'finger1',")
                code_lines.append(f"            parameters: {{ pointerType: 'touch' }},")
                code_lines.append(f"            actions: [")
                code_lines.append(f"                {{ type: 'pointerMove', duration: 0, x: {x}, y: {y} }},")
                code_lines.append(f"                {{ type: 'pointerDown', button: 0 }},")
                code_lines.append(f"                {{ type: 'pause', duration: 100 }},")
                code_lines.append(f"                {{ type: 'pointerUp', button: 0 }}")
                code_lines.append(f"            ]")
                code_lines.append(f"        }}]);")
                
        elif action_type == 'swipe':
            x2 = action.get('x2', x)
            y2 = action.get('y2', y)
            duration = action.get('duration', 500)
            
            # Modern W3C actions for swipe
            code_lines.append(f"        await driver.performActions([{{")
            code_lines.append(f"            type: 'pointer',")
            code_lines.append(f"            id: 'finger1',")
            code_lines.append(f"            parameters: {{ pointerType: 'touch' }},")
            code_lines.append(f"            actions: [")
            code_lines.append(f"                {{ type: 'pointerMove', duration: 0, x: {x}, y: {y} }},")
            code_lines.append(f"                {{ type: 'pointerDown', button: 0 }},")
            code_lines.append(f"                {{ type: 'pause', duration: 50 }},")
            code_lines.append(f"                {{ type: 'pointerMove', duration: {duration}, x: {x2}, y: {y2} }},")
            code_lines.append(f"                {{ type: 'pointerUp', button: 0 }}")
            code_lines.append(f"            ]")
            code_lines.append(f"        }}]);")
            
        elif action_type == 'wait':
            duration = action.get('duration', 1000)
            code_lines.append(f"        await driver.pause({duration});")
        
        code_lines.append("")
    
    code_lines.extend([
        "        console.log('✅ Test completed successfully!');",
        "",
        "    } catch (error) {",
        "        console.error('❌ Test failed:', error);",
        "        throw error;",
        "    } finally {",
        "        await driver.deleteSession();",
        "    }",
        "}",
        "",
        "// Run the test",
        "runTest().catch(console.error);",
    ])
    
    return '\n'.join(code_lines)


def generate_python_code(actions: list) -> str:
    """Generate Python/Appium code from actions"""
    
    code_lines = [
        "# Generated by GravityQA - Automated Test",
        "# Date: " + str(__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')),
        "",
        "from appium import webdriver",
        "from appium.webdriver.common.appiumby import AppiumBy",
        "from selenium.webdriver.common.actions import interaction",
        "from selenium.webdriver.common.actions.action_builder import ActionBuilder",
        "from selenium.webdriver.common.actions.pointer_input import PointerInput",
        "import time",
        "",
        "def run_test():",
        "    # Connect to Appium server",
        "    caps = {",
        "        'platformName': 'Android',",
        "        'appium:automationName': 'UiAutomator2',",
        "        'appium:deviceName': 'Android Device',",
        "        # Add your app package/activity here",
        "    }",
        "    ",
        "    driver = webdriver.Remote(",
        "        'http://localhost:4723',",
        "        caps",
        "    )",
        "",
        "    try:",
    ]
    
    for i, action in enumerate(actions, 1):
        action_type = action.get('action', 'tap')
        x = action.get('x', 0)
        y = action.get('y', 0)
        
        code_lines.append(f"        # Step {i}: {action.get('description', action_type)}")
        
        if action_type == 'tap':
            # Check if element has selector
            element = action.get('element', {})
            selector = element.get('selector', {})
            
            if selector and selector.get('value'):
                strategy = selector.get('strategy', 'xpath')
                value = selector.get('value', '')
                
                if strategy == 'id':
                    code_lines.append(f"        driver.find_element(AppiumBy.ID, '{value}').click()")
                else:
                    code_lines.append(f"        driver.find_element(AppiumBy.XPATH, '{value}').click()")
            else:
                # Modern W3C actions for tap
                code_lines.append(f"        actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, 'touch'))")
                code_lines.append(f"        actions.pointer_action.move_to_location({x}, {y})")
                code_lines.append(f"        actions.pointer_action.pointer_down()")
                code_lines.append(f"        actions.pointer_action.pause(0.1)")
                code_lines.append(f"        actions.pointer_action.pointer_up()")
                code_lines.append(f"        actions.perform()")
                
        elif action_type == 'swipe':
            x2 = action.get('x2', x)
            y2 = action.get('y2', y)
            duration = action.get('duration', 500)
            
            # Modern W3C actions for swipe
            code_lines.append(f"        actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, 'touch'))")
            code_lines.append(f"        actions.pointer_action.move_to_location({x}, {y})")
            code_lines.append(f"        actions.pointer_action.pointer_down()")
            code_lines.append(f"        actions.pointer_action.pause(0.05)")
            code_lines.append(f"        actions.pointer_action.move_to_location({x2}, {y2}, duration={duration / 1000})")
            code_lines.append(f"        actions.pointer_action.pointer_up()")
            code_lines.append(f"        actions.perform()")
            
        elif action_type == 'wait':
            duration = action.get('duration', 1000)
            code_lines.append(f"        time.sleep({duration / 1000})")
        
        code_lines.append("")
    
    code_lines.extend([
        "        print('✅ Test completed successfully!')",
        "",
        "    except Exception as e:",
        "        print(f'❌ Test failed: {e}')",
        "        raise",
        "    finally:",
        "        driver.quit()",
        "",
        "",
        "if __name__ == '__main__':",
        "    run_test()",
    ])
    
    return '\n'.join(code_lines)
