"""Code Generator - Convert recorded actions to executable code"""

def generate_javascript_code(actions: list) -> str:
    """Generate WebdriverIO/JavaScript code from actions"""
    
    code_lines = [
        "// Generated by GravityQA - Automated Test",
        "// Date: " + str(__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')),
        "",
        "// INSTALLATION REQUIRED:",
        "// Before running, install dependencies: npm install webdriverio",
        "",
        "const { remote } = require('webdriverio');",
        "",
        "async function runTest() {",
        "    // Connect to Appium server",
        "    const driver = await remote({",
        "        hostname: 'localhost',",
        "        port: 4723,",
        "        capabilities: {",
        "            platformName: 'Android',",
        "            'appium:automationName': 'UiAutomator2',",
        "            'appium:deviceName': 'Android Device',",
        "            // Add your app package/activity here",
        "        }",
        "    });",
        "",
        "    try {",
    ]
    
    for i, action in enumerate(actions, 1):
        action_type = action.get('action', 'tap')
        x = action.get('x', 0)
        y = action.get('y', 0)
        
        code_lines.append(f"        // Step {i}: {action.get('description', action_type)}")
        
        if action_type == 'tap':
            # Check if element has selector
            element = action.get('element', {})
            selector = element.get('selector', {})
            
            if selector and selector.get('value'):
                strategy = selector.get('strategy', 'xpath')
                value = selector.get('value', '')
                
                if strategy == 'id':
                    code_lines.append(f"        await driver.$('id={value}').click();")
                else:
                    code_lines.append(f"        await driver.$('{value}').click();")
            else:
                # Fallback to coordinates
                code_lines.append(f"        await driver.touchAction({{ action: 'tap', x: {x}, y: {y} }});")
                
        elif action_type == 'swipe':
            x2 = action.get('x2', x)
            y2 = action.get('y2', y)
            duration = action.get('duration', 500)
            
            code_lines.append(f"        await driver.touchAction([")
            code_lines.append(f"            {{ action: 'press', x: {x}, y: {y} }},")
            code_lines.append(f"            {{ action: 'wait', ms: {duration} }},")
            code_lines.append(f"            {{ action: 'moveTo', x: {x2}, y: {y2} }},")
            code_lines.append(f"            'release'")
            code_lines.append(f"        ]);")
            
        elif action_type == 'wait':
            duration = action.get('duration', 1000)
            code_lines.append(f"        await driver.pause({duration});")
        
        code_lines.append("")
    
    code_lines.extend([
        "        console.log('✅ Test completed successfully!');",
        "",
        "    } catch (error) {",
        "        console.error('❌ Test failed:', error);",
        "        throw error;",
        "    } finally {",
        "        await driver.deleteSession();",
        "    }",
        "}",
        "",
        "// Run the test",
        "runTest().catch(console.error);",
    ])
    
    return '\n'.join(code_lines)


def generate_python_code(actions: list) -> str:
    """Generate Python/Appium code from actions"""
    
    code_lines = [
        "# Generated by GravityQA - Automated Test",
        "# Date: " + str(__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')),
        "",
        "# INSTALLATION REQUIRED:",
        "# Before running, install dependencies: pip install Appium-Python-Client",
        "",
        "from appium import webdriver",
        "from appium.webdriver.common.appiumby import AppiumBy",
        "from appium.webdriver.common.touch_action import TouchAction",
        "import time",
        "",
        "def run_test():",
        "    # Connect to Appium server",
        "    caps = {",
        "        'platformName': 'Android',",
        "        'appium:automationName': 'UiAutomator2',",
        "        'appium:deviceName': 'Android Device',",
        "        # Add your app package/activity here",
        "    }",
        "    ",
        "    driver = webdriver.Remote(",
        "        'http://localhost:4723',",
        "        caps",
        "    )",
        "",
        "    try:",
    ]
    
    for i, action in enumerate(actions, 1):
        action_type = action.get('action', 'tap')
        x = action.get('x', 0)
        y = action.get('y', 0)
        
        code_lines.append(f"        # Step {i}: {action.get('description', action_type)}")
        
        if action_type == 'tap':
            # Check if element has selector
            element = action.get('element', {})
            selector = element.get('selector', {})
            
            if selector and selector.get('value'):
                strategy = selector.get('strategy', 'xpath')
                value = selector.get('value', '')
                
                if strategy == 'id':
                    code_lines.append(f"        driver.find_element(AppiumBy.ID, '{value}').click()")
                else:
                    code_lines.append(f"        driver.find_element(AppiumBy.XPATH, '{value}').click()")
            else:
                # Fallback to coordinates
                code_lines.append(f"        driver.tap([({x}, {y})])")
                
        elif action_type == 'swipe':
            x2 = action.get('x2', x)
            y2 = action.get('y2', y)
            duration = action.get('duration', 500)
            
            code_lines.append(f"        driver.swipe({x}, {y}, {x2}, {y2}, {duration})")
            
        elif action_type == 'wait':
            duration = action.get('duration', 1000)
            code_lines.append(f"        time.sleep({duration / 1000})")
        
        code_lines.append("")
    
    code_lines.extend([
        "        print('✅ Test completed successfully!')",
        "",
        "    except Exception as e:",
        "        print(f'❌ Test failed: {e}')",
        "        raise",
        "    finally:",
        "        driver.quit()",
        "",
        "",
        "if __name__ == '__main__':",
        "    run_test()",
    ])
    
    return '\n'.join(code_lines)
