"""Code Generator - Convert recorded actions to executable code"""

def generate_javascript_code(actions: list, app_package: str = None, app_activity: str = None) -> str:
    """Generate WebdriverIO/JavaScript code from actions with app configuration"""
    
    # Default app package/activity if not provided
    if not app_package:
        app_package = "com.example.app"
    if not app_activity:
        app_activity = "com.example.app.MainActivity"
    
    code_lines = [
        "// Generated by GravityQA - Automated Test",
        "// Date: " + str(__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')),
        "",
        "// ═══════════════════════════════════════════════════════════",
        "// 🎯 APP CONFIGURATION",
        "// ═══════════════════════════════════════════════════════════",
        "",
        "const APP_CONFIG = {",
        f"    package: '{app_package}',",
        f"    activity: '{app_activity}',",
        "    clearAppDataBeforeLaunch: true,  // Clear app cache/data before test",
        "};",
        "",
        "const { remote } = require('webdriverio');",
        "",
        "async function runTest() {",
        "    console.log('🚀 Starting test...');",
        "    console.log(`📱 App: ${{APP_CONFIG.package}}`);",
        "    console.log(`🎯 Activity: ${{APP_CONFIG.activity}}`);",
        "    ",
        "    // Connect to Appium server",
        "    const driver = await remote({",
        "        hostname: 'localhost',",
        "        port: 4723,",
        "        capabilities: {",
        "            platformName: 'Android',",
        "            'appium:automationName': 'UiAutomator2',",
        "            'appium:deviceName': 'Android Device',",
        "            ",
        "            // ═══════════════════════════════════════════",
        "            // 📦 APP SETTINGS",
        "            // ═══════════════════════════════════════════",
        "            'appium:appPackage': APP_CONFIG.package,",
        "            'appium:appActivity': APP_CONFIG.activity,",
        "            ",
        "            // ═══════════════════════════════════════════",
        "            // 🧹 CLEAR APP DATA (Fresh Start)",
        "            // ═══════════════════════════════════════════",
        "            'appium:noReset': !APP_CONFIG.clearAppDataBeforeLaunch,",
        "            'appium:fullReset': APP_CONFIG.clearAppDataBeforeLaunch,",
        "        }",
        "    });",
        "",
        "    try {",
        "        console.log('✅ Connected to device');",
        "        ",
        "        if (APP_CONFIG.clearAppDataBeforeLaunch) {",
        "            console.log('🧹 App data cleared - Fresh start!');",
        "        }",
        "        ",
        "        console.log('🎬 Starting test steps...');",
        "",
    ]
    
    for i, action in enumerate(actions, 1):
        action_type = action.get('action', 'tap')
        x = action.get('x', 0)
        y = action.get('y', 0)
        
        code_lines.append(f"        // Step {i}: {action.get('description', action_type)}")
        
        if action_type == 'tap':
            element = action.get('element', {})
            selector = element.get('selector', {})
            
            if selector and selector.get('value'):
                strategy = selector.get('strategy', 'xpath')
                value = selector.get('value', '')
                
                if strategy == 'id':
                    code_lines.append(f"        await driver.$('id={value}').click();")
                else:
                    code_lines.append(f"        await driver.$('{value}').click();")
            else:
                code_lines.append(f"        await driver.performActions([{{")
                code_lines.append(f"            type: 'pointer',")
                code_lines.append(f"            id: 'finger1',")
                code_lines.append(f"            parameters: {{ pointerType: 'touch' }},")
                code_lines.append(f"            actions: [")
                code_lines.append(f"                {{ type: 'pointerMove', duration: 0, x: {x}, y: {y} }},")
                code_lines.append(f"                {{ type: 'pointerDown', button: 0 }},")
                code_lines.append(f"                {{ type: 'pause', duration: 100 }},")
                code_lines.append(f"                {{ type: 'pointerUp', button: 0 }}")
                code_lines.append(f"            ]")
                code_lines.append(f"        }}]);")
                
        elif action_type == 'swipe':
            x2 = action.get('x2', x)
            y2 = action.get('y2', y)
            duration = action.get('duration', 500)
            
            code_lines.append(f"        await driver.performActions([{{")
            code_lines.append(f"            type: 'pointer',")
            code_lines.append(f"            id: 'finger1',")
            code_lines.append(f"            parameters: {{ pointerType: 'touch' }},")
            code_lines.append(f"            actions: [")
            code_lines.append(f"                {{ type: 'pointerMove', duration: 0, x: {x}, y: {y} }},")
            code_lines.append(f"                {{ type: 'pointerDown', button: 0 }},")
            code_lines.append(f"                {{ type: 'pause', duration: 50 }},")
            code_lines.append(f"                {{ type: 'pointerMove', duration: {duration}, x: {x2}, y: {y2} }},")
            code_lines.append(f"                {{ type: 'pointerUp', button: 0 }}")
            code_lines.append(f"            ]")
            code_lines.append(f"        }}]);")
            
        elif action_type == 'wait':
            duration = action.get('duration', 1000)
            code_lines.append(f"        await driver.pause({duration});")
        
        code_lines.append("")
    
    code_lines.extend([
        "        console.log('✅ Test completed successfully!');",
        "",
        "    } catch (error) {",
        "        console.error('❌ Test failed:', error);",
        "        throw error;",
        "    } finally {",
        "        await driver.deleteSession();",
        "        console.log('👋 Session closed');",
        "    }",
        "}",
        "",
        "// Run the test",
        "runTest().catch(console.error);",
    ])
    
    return '\n'.join(code_lines)


def generate_python_code(actions: list, app_package: str = None, app_activity: str = None) -> str:
    """Generate Python/Appium code from actions with app configuration"""
    
    if not app_package:
        app_package = "com.example.app"
    if not app_activity:
        app_activity = "com.example.app.MainActivity"
    
    code_lines = [
        "# Generated by GravityQA - Automated Test",
        "# Date: " + str(__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')),
        "",
        "# ═══════════════════════════════════════════════════════════",
        "# 🎯 APP CONFIGURATION",
        "# ═══════════════════════════════════════════════════════════",
        "",
        "APP_CONFIG = {",
        f"    'package': '{app_package}',",
        f"    'activity': '{app_activity}',",
        "    'clear_app_data_before_launch': True,  # Clear app cache/data before test",
        "}",
        "",
        "from appium import webdriver",
        "from appium.webdriver.common.appiumby import AppiumBy",
        "from selenium.webdriver.common.actions import interaction",
        "from selenium.webdriver.common.actions.action_builder import ActionBuilder",
        "from selenium.webdriver.common.actions.pointer_input import PointerInput",
        "import time",
        "",
        "def run_test():",
        "    print('🚀 Starting test...')",
        "    print(f\"📱 App: {APP_CONFIG['package']}\")",
        "    print(f\"🎯 Activity: {APP_CONFIG['activity']}\")",
        "    ",
        "    # Appium capabilities",
        "    caps = {",
        "        'platformName': 'Android',",
        "        'appium:automationName': 'UiAutomator2',",
        "        'appium:deviceName': 'Android Device',",
        "        ",
        "        # ═══════════════════════════════════════════",
        "        # 📦 APP SETTINGS",
        "        # ═══════════════════════════════════════════",
        "        'appium:appPackage': APP_CONFIG['package'],",
        "        'appium:appActivity': APP_CONFIG['activity'],",
        "        ",
        "        # ═══════════════════════════════════════════",
        "        # 🧹 CLEAR APP DATA (Fresh Start)",
        "        # ═══════════════════════════════════════════",
        "        'appium:noReset': not APP_CONFIG['clear_app_data_before_launch'],",
        "        'appium:fullReset': APP_CONFIG['clear_app_data_before_launch'],",
        "    }",
        "    ",
        "    driver = webdriver.Remote(",
        "        'http://localhost:4723',",
        "        caps",
        "    )",
        "",
        "    try:",
        "        print('✅ Connected to device')",
        "        ",
        "        if APP_CONFIG['clear_app_data_before_launch']:",
        "            print('🧹 App data cleared - Fresh start!')",
        "        ",
        "        print('🎬 Starting test steps...')",
        "",
    ]
    
    for i, action in enumerate(actions, 1):
        action_type = action.get('action', 'tap')
        x = action.get('x', 0)
        y = action.get('y', 0)
        
        code_lines.append(f"        # Step {i}: {action.get('description', action_type)}")
        
        if action_type == 'tap':
            element = action.get('element', {})
            selector = element.get('selector', {})
            
            if selector and selector.get('value'):
                strategy = selector.get('strategy', 'xpath')
                value = selector.get('value', '')
                
                if strategy == 'id':
                    code_lines.append(f"        driver.find_element(AppiumBy.ID, '{value}').click()")
                else:
                    code_lines.append(f"        driver.find_element(AppiumBy.XPATH, '{value}').click()")
            else:
                code_lines.append(f"        actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, 'touch'))")
                code_lines.append(f"        actions.pointer_action.move_to_location({x}, {y})")
                code_lines.append(f"        actions.pointer_action.pointer_down()")
                code_lines.append(f"        actions.pointer_action.pause(0.1)")
                code_lines.append(f"        actions.pointer_action.pointer_up()")
                code_lines.append(f"        actions.perform()")
                
        elif action_type == 'swipe':
            x2 = action.get('x2', x)
            y2 = action.get('y2', y)
            duration = action.get('duration', 500)
            
            code_lines.append(f"        actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, 'touch'))")
            code_lines.append(f"        actions.pointer_action.move_to_location({x}, {y})")
            code_lines.append(f"        actions.pointer_action.pointer_down()")
            code_lines.append(f"        actions.pointer_action.pause(0.05)")
            code_lines.append(f"        actions.pointer_action.move_to_location({x2}, {y2}, duration={duration / 1000})")
            code_lines.append(f"        actions.pointer_action.pointer_up()")
            code_lines.append(f"        actions.perform()")
            
        elif action_type == 'wait':
            duration = action.get('duration', 1000)
            code_lines.append(f"        time.sleep({duration / 1000})")
        
        code_lines.append("")
    
    code_lines.extend([
        "        print('✅ Test completed successfully!')",
        "",
        "    except Exception as e:",
        "        print(f'❌ Test failed: {e}')",
        "        raise",
        "    finally:",
        "        driver.quit()",
        "        print('👋 Session closed')",
        "",
        "",
        "if __name__ == '__main__':",
        "    run_test()",
    ])
    
    return '\n'.join(code_lines)
